import random

def generate_insult(name, simple_insult):
    phrases = [
        f"You, {name}, are nothing but a {simple_insult}!",
        f"Your {simple_insult}, {name}, is as useful as a screen door on a submarine!",
        f"{name}, you're a complete and utter {simple_insult}!",
        f"I can't believe someone as {simple_insult} as you, {name}, exists!",
        f"{name}, you're about as sharp as a marble, you {simple_insult}!",
        f"Listening to you, {name}, is like trying to understand a cow mooing - pointless and irritating!",
        f"{name}, you're such a {simple_insult} that even a dumpster fire is jealous of your stupidity!",
        f"Congratulations, {name}, you've managed to become the epitome of {simple_insult}!",
        f"I wouldn't trust you, {name}, to find your way out of a wet paper bag!",
        f"{name}, you're so {simple_insult} that even Siri couldn't find any useful information about you!",
        f"Hey, {name}, did it take you long to come up with that {simple_insult}? Because it's utterly unimaginative!",
        f"{name}, your level of {simple_insult} is truly awe-inspiring. Not in a good way, though!",
        f"Have you ever considered a career in being a professional {simple_insult}, {name}? You'd excel at it!",
        f"I have met fungi with more intelligence than you, {name}, and they don't even have brains!",
        f"{name}, you're the living embodiment of a bad hair day - just utterly {simple_insult}!",
        f"Even a broken clock is right twice a day, {name}, but you manage to be wrong all day, every day!",
        f"{name}, you're the reason why aliens won't talk to us. They're afraid of catching your {simple_insult}!",
        f"You must be so proud, {name}, of being the poster child for {simple_insult}!",
        f"{name}, I'm amazed at how you manage to consistently lower the bar for human intelligence!",
        f"{name}, if there was a contest for being the most {simple_insult}, you'd win first place without even trying!",
        f"Hey {name}, here's a thought - try using your brain for once. You might surprise yourself, you {simple_insult}!",
        f"{name}, you're like a vacuum cleaner for happiness - wherever you go, joy disappears!",
        f"I have better conversations with my pet rock than with you, {name}, you {simple_insult}!",
        f"May the fleas of a thousand camels infest your armpits, {name}, you {simple_insult}!",
        f"{name}, your existence is a constant reminder that natural selection isn't always perfect!",
        f"I could explain it to you, {name}, but I can't understand it for you. That's impossible even for me!",
        f"{name}, your intelligence is like a black hole - it sucks everything in and nothing escapes!",
        f"{name}, I'm not saying you're stupid, but if there was a stupid Olympics, you'd definitely win a gold medal!",
        f"Is there a limit to your {simple_insult}, {name}? Because you seem to surpass it every single time!",
        f"{name}, your IQ is so low that it's considered an endangered species!",
        f"You have all the charm and wit of a moldy potato, {name}. Actually, that's an insult to potatoes!",
        f"{name}, you're the reason why we can't have nice things. Your {simple_insult} ruins everything!",
        f"I'm not sure what's worse, {name} - your {simple_insult} or the fact that you're proud of it!",
        f"{name}, you're like a broken pencil - pointless and completely {simple_insult}!",
        f"I'd call you a {simple_insult}, {name}, but that would be an insult to {simple_insult}s everywhere!",
        f"{name}, you're so dense that light bends around you! Talk about being {simple_insult}!",
        f"Your level of {simple_insult}, {name}, is a constant source of entertainment for everyone else!",
        f"{name}, your IQ is so low, it's in negative territory. Congrats on achieving the impossible!",
        f"Every time you open your mouth, {name}, the world becomes a slightly dumber place. Keep it up, you {simple_insult}!",
        f"{name}, if ignorance was a superpower, you'd be a superhero!",
        f"Have you ever considered donating your brain to science, {name}? It would be an interesting case study in {simple_insult}!",
        f"{name}, your stupidity is a shining example of what happens when the stars align in the dumbest way possible!",
        f"You must have a Ph.D. in {simple_insult}, {name}, because you're a true expert in the field!",
        f"Can you do us all a favor, {name}, and disappear? The world would instantly become a smarter place!",
        f"{name}, if a thought crossed your mind, it would probably get lost in the vast void of your {simple_insult}!",
        f"You, {name}, are living proof that evolution sometimes takes a step backward!",
        f"{name}, I'm amazed at how well you manage to function with so few brain cells!",
        f"{name}, if laughter is the best medicine, you should be a doctor. You're a constant source of amusement!",
        f"Your {simple_insult}, {name}, is like a train wreck - horrifying to witness, yet impossible to look away from!",
        f"{name}, you're a walking advertisement for birth control. People take one look at you and decide not to procreate!",
        f"Hey {name}, here's a thought - try thinking before you speak. I know it's a novel concept for you!",
        f"{name}, your stupidity is so powerful that it could single-handedly solve the world's energy crisis!",
        f"{name}, you're like a closed book - dull, uninteresting, and full of {simple_insult}!",
        f"I'm convinced that if brains were rain, {name}, you'd be in a permanent drought!",
        f"{name}, you're the reason why the gene pool needs a lifeguard!",
        f"{name}, your brain is like a black hole - it sucks in knowledge and emits only {simple_insult}!",
        f"I'd call you a {simple_insult}, {name}, but that would be an insult to {simple_insult}s worldwide!",
        f"{name}, your {simple_insult} is so legendary that it deserves its own documentary!",
        f"{name}, your brain is a prime example of why some animals eat their young!",
        f"I'd say you're dumber than a box of rocks, {name}, but that would be an insult to rocks everywhere!",
        f"{name}, your lack of intelligence is staggering. It's a wonder you manage to get dressed in the morning!",
        f"You, {name}, are living proof that stupidity knows no bounds!",
        f"{name}, I'd try to explain your {simple_insult} to you, but I fear it would only confuse you further!",
        f"I'm not sure who dropped you on your head as a child, {name}, but I'd like to have a word with them!",
        f"{name}, your stupidity is so monumental that it should be studied by scientists!",
        f"I bet your parents look at you, {name}, and wonder where they went wrong!",
        f"{name}, you're the human equivalent of a participation trophy - utterly pointless!",
        f"Is your purpose in life, {name}, to be a cautionary tale for others? If so, you're doing a fantastic job!",
        f"{name}, your brain is so tiny that a single neuron would be considered an upgrade!",
        f"You, {name}, are a shining example of why some animals eat their young!",
        f"{name}, your intelligence is on par with that of a rock, and I apologize to rocks everywhere for the comparison!",
        f"Every time I think you've reached the pinnacle of {simple_insult}, {name}, you somehow manage to exceed my expectations!",
        f"{name}, I've seen more intelligence in a box of crayons than I've seen in you!",
        f"{name}, your {simple_insult} is so potent that it could be weaponized and used against our enemies!",
        f"{name}, it's truly impressive how you manage to consistently make the wrong decisions in every aspect of your life!",
        f"Are you intentionally trying to be {simple_insult}, {name}, or does it come naturally to you?",
        f"{name}, you're a walking advertisement for the importance of education. Clearly, you missed the memo!",
        f"{name}, if stupidity was an Olympic sport, you'd win the gold medal every single time!",
        f"{name}, you're like a mosquito - irritating, useless, and nobody wants you around!",
        f"Your {simple_insult}, {name}, is like a contagious disease - it spreads stupidity wherever you go!",
        f"{name}, your brain must be full of cobwebs because it seems like rational thoughts rarely enter!",
        f"I've met cardboard cutouts with more personality and intelligence than you, {name}!",
        f"{name}, you're a living example of why some species eat their own young!",
        f"{name}, you have the decision-making skills of a squirrel on caffeine. It's truly impressive!",
        f"I'm amazed, {name}, at how well you manage to function with such a limited capacity for rational thought!",
        f"{name}, the fact that you can tie your shoes without assistance is a testament to human perseverance!",
        f"Your {simple_insult}, {name}, is like a bad odor - it lingers and makes everyone uncomfortable!",
        f"{name}, your level of {simple_insult} is truly awe-inspiring. In all the wrong ways!",
        f"You're like a human version of a car alarm, {name} - noisy, irritating, and completely unnecessary!",
        f"{name}, I'd say your brain is the size of a pea, but that would be an insult to peas!",
        f"{name}, you're so {simple_insult} that you make a rock look like a genius in comparison!",
        f"Even a malfunctioning GPS is more capable of finding its way than you, {name}!",
        f"{name}, the world would be a smarter place if you just stopped talking altogether!",
        f"You, {name}, are the living embodiment of the saying 'empty vessels make the most noise'!",
        f"{name}, you're like a broken record - repeating the same {simple_insult} over and over again!",
        f"{name}, I have socks that are smarter than you. And I'm not even wearing any socks right now!",
        f"{name}, your {simple_insult} is so legendary that it deserves a spot in the history books!",
        f"I'd say you're as useful as a chocolate teapot, {name}, but that would be an insult to chocolate!",
        f"{name}, your stupidity is so remarkable that it could be considered a work of art!",
        f"{name}, you're the reason why warning labels exist. People like you need instructions for everything!",
    ]

    insult = random.choice(phrases)
    return insult

# Example usage
name = input("Enter the name of the person insulted: ")
simple_insult = input("Enter a simple insult: ")
insults = [generate_insult(name, simple_insult) for _ in range(5)]
for insult in insults:
    print(insult)
    