import random

# List of 100 random questions covering various topics
questions = [
    "What is your favorite book and why?",
    "If you could travel anywhere in the world right now, where would you go?",
    "What's the most adventurous thing you've ever done?",
    "What's your favorite memory from your childhood?",
    "If you could have any superpower, what would it be?",
    "What are your top three favorite movies of all time?",
    "What do you value the most in a friendship?",
    "If you had a time machine, which era would you visit?",
    "What's the most important lesson life has taught you so far?",
    "What's your dream job, and why?",
    "If you could meet any historical figure, who would it be?",
    "What's one thing you'd like to change about the world?",
    "What's your favorite way to relax and unwind?",
    "If you could learn to do anything, what skill would you choose?",
    "What are your favorite hobbies or interests?",
    "What's the best piece of advice you've ever received?",
    "What's your go-to comfort food?",
    "What's the most meaningful gift you've ever received?",
    "If you could have dinner with any three people, dead or alive, who would you choose?",
    "What's your favorite thing about yourself?",
    "What's the most beautiful place you've ever been to?",
    "What's one thing you've always wanted to try but haven't had the chance?",
    "What are your top three favorite songs at the moment?",
    "If you could live in any fictional universe, which one would you choose?",
    "What's a skill you'd like to master in the future?",
    "What's the best part about being your age?",
    "What's one habit you wish you could break?",
    "What's the most interesting documentary you've watched?",
    "If you could switch lives with someone for a day, who would it be?",
    "What's something that always makes you smile?",
    "What's your favorite way to exercise or stay active?",
    "If you could have any pet, exotic or not, what would you choose?",
    "What's a topic you could talk about for hours?",
    "What's your favorite season and why?",
    "What's a place you've always wanted to visit but haven't yet?",
    "If you could learn any language instantly, which one would you pick?",
    "What's your favorite way to give back to the community?",
    "What's your proudest accomplishment so far?",
    "If you had a warning label, what would it say?",
    "What's the best compliment you've ever received?",
    "What's something you're currently trying to improve in your life?",
    "What's a random act of kindness you've done or received?",
    "If you could live in any time period, which one would you choose?",
    "What's the most daring thing you've ever done?",
    "What's your favorite family tradition?",
    "If you could be an expert in any field, what would it be?",
    "What's one thing you're grateful for today?",
    "What's your favorite type of cuisine?",
    "If you could eliminate one thing from your daily routine, what would it be?",
    "What's a piece of technology you can't live without?",
    "What's your favorite form of art (e.g., painting, music, dance)?",
    "If you could witness any historical event, which one would you choose?",
    "What's your favorite way to de-stress?",
    "If you could give your younger self one piece of advice, what would it be?",
    "What's the best vacation you've ever been on?",
    "What's one skill you wish everyone in the world had?",
    "If you could master any instrument, which one would you pick?",
    "What's the most spontaneous thing you've ever done?",
    "What's the best piece of advice you've given to someone?",
    "What's your favorite board game or video game?",
    "If you could have a dinner party with five celebrities, who would you invite?",
    "What's a fashion trend you wish would come back?",
    "What's the most adventurous food you've ever tried?",
    "If you could spend a day with any animal, which one would you choose?",
    "What's your favorite way to celebrate your birthday?",
    "If you could have a conversation with your future self, what would you ask?",
    "What's one thing you'd like to achieve in the next year?",
    "What's the best piece of advice you've received from a friend?",
    "What's the most challenging thing you've ever done?",
    "If you could have any celebrity play you in a movie, who would it be?",
    "What's your favorite way to show kindness to others?",
    "What's something that never fails to make you laugh?",
    "If you could instantly learn any profession, which one would you choose?",
    "What's your favorite way to spend a rainy day?",
    "What's the most interesting museum you've visited?",
    "If you could invent a new flavor of ice cream, what would it be?",
    "What's a habit you're glad you developed?",
    "What's your favorite way to learn new things?",
    "If you could attend any major event in history, which one would you go to?",
    "What's a movie or book that has had a significant impact on you?",
    "What's the most meaningful gift you've ever given to someone?",
    "If you could have any job for a day, what would it be?",
    "What's the best part about your current stage of life?",
    "What's a topic you wish more people knew about?",
    "If you could have any animal as a pet, which one would you choose?",
    "What's the best compliment you've ever given to someone?",
    "What's something you've recently accomplished that you're proud of?",
    "If you could have any mythical creature as a companion, what would it be?",
    "What's your favorite way to stay motivated?",
    "What's one place you've always wanted to live?",
    "What's the most significant lesson you've learned from a failure?",
    "What's your favorite way to celebrate special occasions?",
    "If you could time travel to the past or the future, which would you choose and why?",
    "What's the most interesting documentary you've watched?",
    "What's one thing you'd like to learn more about?",
    "What's your favorite thing about the changing seasons?",
    "If you could have any talent or skill instantly, which one would it be?",
    "What's a recent act of kindness you've witnessed or experienced?",
]

def random_question_generator():
    return random.choice(questions)

def main():
    while True:
        input("Press 'n' for a new question or any other key to quit: ")
        question = random_question_generator()
        print(question)

if __name__ == "__main__":
    main()